version: '3.8'

services:
  ocr-pymupdf:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ocr-pymupdf
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"  # Para la documentación MkDocs
    volumes:
      - .:/app
      - ./pdfs:/app/pdfs
      - ./resultado:/app/resultado
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app/src
      # OpenAI
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL_ID=${OPENAI_MODEL_ID:-gpt-3.5-turbo}
      - OPENAI_MAX_RETRIES=${OPENAI_MAX_RETRIES:-5}
      # Gemini
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL_ID=${GEMINI_MODEL_ID:-gemini-pro}
      - GEMINI_MAX_RETRIES=${GEMINI_MAX_RETRIES:-5}
      # DeepSeek
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DEEPSEEK_MODEL_ID=${DEEPSEEK_MODEL_ID:-deepseek-chat}
      - DEEPSEEK_MAX_RETRIES=${DEEPSEEK_MAX_RETRIES:-5}
      - DEEPSEEK_TEMPERATURE=${DEEPSEEK_TEMPERATURE:-0.3}
      # Development
      - PYTHONBREAKPOINT=ipdb.set_trace
      - PYTEST_ADDOPTS=--color=yes
    command: tail -f /dev/null