services:
  ocr-pymupdf:
    build: .
    container_name: ocr-pymupdf
    volumes:
      - ./pdfs:/app/pdfs
      - ./resultado:/app/resultado
      - ./src:/app/src
      - ./data:/app/data
      - ./tests:/app/tests
    environment:
      - PYTHONPATH=/app/src
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - deepseek
    networks:
      - ocr_network

  deepseek:
    build:
      context: .
      dockerfile: docker/deepseek/Dockerfile
    container_name: deepseek-llm
    volumes:
      - ./models:/app/models
    environment:
      - MODEL_ID=deepseek-ai/deepseek-coder-33b-instruct
    environment:
      - MODEL_ID=deepseek-ai/deepseek-coder-1.3b-instruct
      - USE_INT8=true
    ports:
      - "8000:8000"
    networks:
      - ocr_network

networks:
  ocr_network:
    driver: bridge
      - ./tests/fixtures:/app/tests/fixtures
      - fasttext_models:/app/data/models/fasttext
    stdin_open: true
    tty: true
    environment:
      - PYTHONPATH=/app/src
      - OPENAI_API_KEY
      - OPENAI_ORG_ID
      - OPENAI_PROMPT_MODEL
      - OPENAI_FT_MODEL
      - OCR_DPI=300

volumes:
  fasttext_models: {}