services:
  ocr-pymupdf:
    build: .
    container_name: ocr-pymupdf
    volumes:
      - ./pdfs:/app/pdfs
      - ./resultado:/app/resultado
      - ./src:/app/src
      - ./data:/app/data
      - ./tests:/app/tests
    environment:
      - PYTHONPATH=/app/src
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - deepseek
    networks:
      - ocr_network

  deepseek:
    build:
      context: .
      dockerfile: docker/deepseek/Dockerfile
    container_name: deepseek-llm
    volumes:
      - ./models:/app/models
    environment:
      - MODEL_ID=deepseek-ai/deepseek-coder-6.7b-instruct
      - USE_INT8=true
      - USE_MMAP=true
      - DEVICE=mps
      - USE_FLASH_ATTENTION=true
      - MAX_BATCH_SIZE=4
      - NUM_THREADS=8
    ports:
      - "8000:8000"
    networks:
      - ocr_network

networks:
  ocr_network:
    driver: bridge

volumes:
  fasttext_models: {}