services:
  ocr-pymupdf:
    build: .
    container_name: ocr-pymupdf
    volumes:
      - ./pdfs:/app/pdfs
      - ./resultado:/app/resultado
      - ./tests:/app/tests
      - ./tests/fixtures:/app/tests/fixtures       
    stdin_open: true
    tty: true
    environment:
      - PYTHONPATH=/app/src
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: tail -f /dev/null